package org.mitre.mandolin.predict

/*
 * Copyright (c) 2014-2015 The MITRE Corporation
 */

/**
  * Constructs an arbitrary output representation based on the original input representation
  * along with the response generated by a decoder/predictor object. As an example, an input type
  * could be a string such as an English sentence, the response type could be a sequence of part of
  * speech tags (generated by the decoder/predictor) object and the output type could be SGML/XML
  * or some other representation associating the results of the prediction (pos tags) with the original
  * input.
  *
  * @tparam IType input type
  * @tparam R     response of decoder/predictor
  * @tparam OType output representation
  */
abstract class OutputConstructor[IType, R, OType] extends Serializable {
  def constructOutput(input: IType, response: R, tunitStr: String): OType

  def responseString(r: R): String // maps response to a string for pretty-printing
  def intToResponseString(i: Int): String // for discrete responses indexed as integers (very common case)
}

